[dev]
  command = "node index.js"
  targetPort = 3001
  port = 8888
  framework = "#custom"
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/api/:splat"
  status = 200
  force = true
